# Generated by Django 4.2.4 on 2023-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
