# Generated by Django 4.2.4 on 2023-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_author_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_of_publish',
            field=models.IntegerField(null=True),
        ),
    ]
